# Generated by Django 6.0.2 on 2026-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaignlead_last_sent_message_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencestep",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("WHATSAPP", "WhatsApp"),
                    ("LINKEDIN", "LinkedIn"),
                    ("WAIT", "Wait"),
                    ("MANUAL", "Manual Task"),
                    ("CONDITION_OPEN", "Condition: Opened Email"),
                    ("CONDITION_REPLY", "Condition: Replied"),
                    ("CONDITION_CLICK", "Condition: Clicked Link"),
                ],
                max_length=20,
            ),
        ),
    ]
