# Generated by Django 6.0.2 on 2026-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_connectedemailaccount_connected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlead",
            name="last_clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignlead",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignlead",
            name="last_replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
