# Generated by Django 5.2.11 on 2026-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_campaignlead_last_clicked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencestep",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("CALL", "Phone Call"),
                    ("WHATSAPP", "WhatsApp"),
                    ("LINKEDIN", "LinkedIn"),
                    ("WAIT", "Wait"),
                    ("MANUAL", "Manual Task"),
                    ("CONDITION_OPEN", "Condition: Opened Email"),
                    ("CONDITION_REPLY", "Condition: Replied"),
                    ("CONDITION_CLICK", "Condition: Clicked Link"),
                ],
                max_length=20,
            ),
        ),
    ]
